### ISSUE TITLE
Pock closes immediately on launching

### ISSUE THREAD

**Issue by AjitZero** [pigigaldi/Pock#15]
When I launch Pock, it momentarily shows the dock on my Touchbar but disappears _under 1 second_. I haven't been able to make it work at all.

Clicking on an app through the Touchbar _before_ it disappears **works**.

I'm on Mac OS X 10.14.2 and will be updating it this weekend. I'll update this issue if there is any change after the update.

Crash file (renamed *.crash to *.txt for GitHub): [Pock_2019-03-27-020039_Origins.txt](https://github.com/pigigaldi/Pock/files/3010204/Pock_2019-03-27-020039_Origins.txt)

**Comment by eastpiger** [comment]
same issue here

**Comment by remus-b** [comment]
Same here. Doesn't work. I'm on 10.14.3

**Comment by pigigaldi** [comment]
Thanks for the feedbacks, I’ll check this issue asap!

**Comment by sergiootorre** [comment]
Even when i go to preferences and choose to launch at login, it doesn't save. Pock closes everytime i lock my screen. It's a great and congrats for that but for now i had to put it at my dock so that i can launch it. ;)

**Comment by mdgmichael** [comment]
I'm having the same issue. Attached my crash file in case it helps! Looks pretty similar to AjitZero’s.
[Pock_2019-03-28-131028_Amethyst.txt](https://github.com/pigigaldi/Pock/files/3019375/Pock_2019-03-28-131028_Amethyst.txt)

**Comment by tuchief** [comment]
10.14.4 also has the same problem

**Comment by Tatsh** [comment]
The fix is:

```patch
diff --git a/Pock/Widgets/Dock/PockUtilities.swift b/Pock/Widgets/Dock/PockUtilities.swift
index 6513250..84e1a2b 100644
--- a/Pock/Widgets/Dock/PockUtilities.swift
+++ b/Pock/Widgets/Dock/PockUtilities.swift
@@ -87,7 +87,7 @@ public class PockUtilities {

             /// Add bundle identifier to returnable array.
             let dockItem = PockItem(label: label, bundleIdentifier: bundleIdentifier, icon: PockUtilities.ge
tIcon(forBundleIdentifier: bundleIdentifier))
-            returnable.insert(dockItem, at: ind)
+            returnable.append(dockItem)

         }
```

**Comment by Tatsh** [comment]
Perhaps you guys have [spacer Dock entries](https://www.macrumors.com/how-to/group-app-icons-macos-dock/) like me?

**Comment by remus-b** [comment]
Yes, I can confirm, I have spacer Dock entries :D @Tatsh

**Comment by MotoX450** [comment]
I do not have spacer Dock entries and I am facing this issues (10.13.6).

**Comment by pigigaldi** [comment]
Keep visit http://pock.pigigaldi.com, an update will be available soon that should fix this issue too.

**Comment by eastpiger** [comment]
yes :D I have lots of spacer Dock entries LOL

**Comment by mdgmichael** [comment]
@Tatsh Good call! I removed my spacers and now it runs fine. I will of course grab the fix when it's available, but I don't mind going spacerless for a little while so I can start playing with Pock. :)

**Comment by woolson** [comment]
@pigigaldi still crash on start up.

MBP: MacBook Pro (15-inch, 2017)
   OS: 10.14.4 (18E226)
 
![image](https://user-images.githubusercontent.com/27878293/55253076-5288aa80-528f-11e9-804f-7b382246dc7a.png)

**Comment by pigigaldi** [comment]
Thanks for the feedback! Maybe I need more time to investigate these cases.

**Comment by pigigaldi** [comment]
#25
